#!/usr/bin/env bash

# Define the repository URL and the download path
REPO_URL="https://github.com/rocketpowerinc/assets.git"
DOWNLOAD_PATH="$HOME/Downloads/assets"

# Clean up
rm -rf "$DOWNLOAD_PATH"

# Clone the repository
git clone "$REPO_URL" "$DOWNLOAD_PATH" || {
  echo "Failed to clone the repository."
  exit 1
}

#* Wallpapers
sudo mkdir -p /usr/share/backgrounds
sudo find "$DOWNLOAD_PATH/wallpapers/" -type f -exec mv {} /usr/share/backgrounds/ \;

#* Icons
sudo mkdir -p /usr/share/icons
sudo find "$DOWNLOAD_PATH/icons/" -type f -exec mv {} /usr/share/icons/ \;


# Clean up
rm -rf "$DOWNLOAD_PATH"
